### ISSUE TITLE
block in load_missing_constant': uni nitialized constant Textlocal (NameError)

### ISSUE THREAD

**Issue by ajit123jain** [sajan45/textlocal-india#1]
Unable to initialize the Textlocal object

**Comment by sajan45** [comment]
If you are using it in Rails then, in Gemfile try giving an explicit name.
`gem 'textlocal-india', require: 'textlocal'`

**Comment by sajan45** [comment]
Version **0.1.2** should work in Rails.

**Comment by ajit123jain** [comment]
Ok I will try.

**Comment by ajit123jain** [comment]
No field is there like username only apikey is there

**Comment by sajan45** [comment]
They have changed their API request parameters as they don't need username now and api key is now called as api_key whereas before it was api_hash. Unfortunately, I never used TextLocal after the initial testing phase. So, I have not updated this gem since then. I am using msgwow.com now as they are cheaper. Anyway, the gem is a simple wrapper around the HTTP calls, feel free to fork and modify necessary files.
